[profile.default]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200


remappings = [
    "@foundry-rs/=lib/foundry-rs/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "forge-gas-snapshot/=lib/v4-core/lib/forge-gas-snapshot/src/",
    "permit2/=lib/v4-periphery/lib/permit2/",
    "solmate/=lib/v4-core/lib/solmate/",
    "v4-core/src/=lib/v4-core/src/",
    "v4-periphery/src/=lib/v4-periphery/src/",
    "@signprotocol/signprotocol-evm=lib/sign-protocol-evm",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
